# Generated by Django 5.2.14 on 2026-06-05 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_squashed_wagtail_removed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('meta_title', models.CharField(blank=True, help_text='Preporučeno: 50–60 karaktera. Prazno = naslov stranice.', max_length=70, verbose_name='Meta naslov')),
                ('meta_description', models.TextField(blank=True, help_text='Preporučeno: 150–160 karaktera.', max_length=320, verbose_name='Meta opis')),
                ('title', models.CharField(max_length=255, verbose_name='Naslov')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, verbose_name='Uvod')),
                ('featured_image', models.ImageField(blank=True, storage='blog_images', upload_to='blog/featured/%Y/%m/', verbose_name='Istaknuta slika')),
                ('publish_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum objave')),
                ('is_published', models.BooleanField(default=False, verbose_name='Objavljeno')),
            ],
            options={
                'verbose_name': 'Blog objava',
                'verbose_name_plural': 'Blog objave',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
