# Generated by Django 5.2.14 on 2026-06-05 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Ostavite prazno — automatski se generiše sa javne adrese stranice.', verbose_name='Kanonski URL'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Kratak tekst na kartici bloga. Prazno = koristi se meta opis.', verbose_name='Uvod'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Prikazuje se na kartici u listi bloga. Sadržaj članka gradi se u builderu ispod.', storage='blog_images', upload_to='blog/featured/%Y/%m/', verbose_name='Istaknuta slika'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Samo objavljene objave su vidljive na sajtu.', verbose_name='Objavljeno'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Datum prikazan posetiocima.', verbose_name='Datum objave'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(help_text='Deo URL adrese (npr. priprema-podloge). Generiše se iz naslova.', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Naslov članka — koristi se u kartici na listi bloga i u pretrazi.', max_length=255, verbose_name='Naslov'),
        ),
    ]
