# Generated by Django 5.2.15 on 2026-06-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_canonical_url_alter_blogpost_excerpt_and_more'),
        ('seo', '0002_migrate_legacy_seo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_title',
        ),
    ]
