# Generated by Django 5.2.15 on 2026-06-06 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_legacy_seo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('name', models.CharField(max_length=120, verbose_name='Naziv')),
                ('slug', models.SlugField(help_text='Deo URL adrese kategorije, npr. cementne-kosuljice.', max_length=120, verbose_name='Slug')),
                ('breadcrumb_title', models.CharField(blank=True, help_text='Prazno = naziv kategorije.', max_length=100, verbose_name='Naslov u breadcrumb-u')),
                ('description', models.TextField(blank=True, help_text='Kratak opis za stranicu kategorije i SEO.', verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivna')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.blogcategory', verbose_name='Nadkategorija')),
            ],
            options={
                'verbose_name': 'Blog kategorija',
                'verbose_name_plural': 'Blog kategorije',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Koristi se za hijerarhijske breadcrumb stavke i filtriranje.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='Kategorija'),
        ),
        migrations.AddConstraint(
            model_name='blogcategory',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='blog_category_unique_slug_per_parent'),
        ),
    ]
