# Generated by Django 5.2.15 on 2026-06-07 06:53

import apps.core.storage_aliases
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Prikazuje se na kartici u listi bloga. Sadržaj članka gradi se u builderu ispod.', storage=apps.core.storage_aliases.blog_images_storage, upload_to='blog/featured/%Y/%m/', verbose_name='Istaknuta slika'),
        ),
    ]
