# Generated by Django 5.2.16 on 2026-07-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_document_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body_plaintext',
            field=models.TextField(blank=True, editable=False, help_text='Automatski izvučen iz page JSON-a za pretragu i SEO.', verbose_name='Sadržaj (običan tekst)'),
        ),
    ]
