# Generated by Django 5.2.16 on 2026-07-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogpost_body_plaintext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='page_version',
            field=models.PositiveIntegerField(default=0, help_text='Raste monotono pri svakoj promeni page sadržaja (čuvanje, konflikti, revizije).', verbose_name='Verzija stranice'),
        ),
    ]
