# Generated by Django 5.2.16 on 2026-07-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blogpost_page_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Kratak sažetak za karticu bloga, meta opis (ako je prazan), društvene mreže i AI preglede. Jedno polje — više izlaza.', verbose_name='Uvod'),
        ),
    ]
