# Generated by Django 5.2.16 on 2026-07-17 10:33

import apps.core.storage_aliases
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blogpost_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Prikazuje se na kartici u listi bloga i u zaglavlju članka.', storage=apps.core.storage_aliases.blog_images_storage, upload_to='page/featured/%Y/%m/', verbose_name='Istaknuta slika'),
        ),
    ]
