# Generated by Django 5.2.15 on 2026-06-06 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='ID sadržaja')),
                ('seo_title', models.CharField(blank=True, help_text='Preporučeno: 50–60 karaktera. Prazno = naslov sadržaja.', max_length=70, verbose_name='SEO naslov')),
                ('meta_description', models.TextField(blank=True, help_text='Preporučeno: 150–160 karaktera. Prazno = uvod ili tekst iz buildera.', max_length=320, verbose_name='Meta opis')),
                ('focus_keyword', models.CharField(blank=True, max_length=100, verbose_name='Fokus ključna reč')),
                ('secondary_keywords', models.CharField(blank=True, help_text='Odvojite zarezom, npr. cement, fasada, temelj.', max_length=255, verbose_name='Sekundarne ključne reči')),
                ('canonical_url', models.URLField(blank=True, help_text='Prazno = automatski sa javne adrese stranice.', verbose_name='Kanonski URL')),
                ('robots_index', models.BooleanField(default=True, help_text='Isključite za noindex.', verbose_name='Robots: index')),
                ('robots_follow', models.BooleanField(default=True, help_text='Isključite za nofollow.', verbose_name='Robots: follow')),
                ('og_title', models.CharField(blank=True, help_text='Prazno = SEO naslov.', max_length=70, verbose_name='Open Graph naslov')),
                ('og_description', models.TextField(blank=True, help_text='Prazno = meta opis.', max_length=320, verbose_name='Open Graph opis')),
                ('og_image', models.ImageField(blank=True, help_text='Prazno = istaknuta slika ili prva slika iz buildera.', storage='blog_images', upload_to='seo/og/%Y/%m/', verbose_name='Open Graph slika')),
                ('twitter_title', models.CharField(blank=True, help_text='Prazno = Open Graph naslov.', max_length=70, verbose_name='Twitter naslov')),
                ('twitter_description', models.TextField(blank=True, help_text='Prazno = Open Graph opis.', max_length=320, verbose_name='Twitter opis')),
                ('twitter_image', models.ImageField(blank=True, help_text='Prazno = Open Graph slika.', storage='blog_images', upload_to='seo/twitter/%Y/%m/', verbose_name='Twitter slika')),
                ('is_cornerstone', models.BooleanField(default=False, help_text='Označite ključne, strateški važne stranice ili članke.', verbose_name='Cornerstone sadržaj')),
                ('breadcrumb_title', models.CharField(blank=True, help_text='Prazno = SEO naslov.', max_length=100, verbose_name='Naslov u breadcrumb-u')),
                ('schema_type', models.CharField(blank=True, choices=[('', 'Automatski (preporučeno)'), ('WebPage', 'WebPage'), ('Article', 'Article'), ('BlogPosting', 'BlogPosting'), ('Service', 'Service'), ('FAQPage', 'FAQPage'), ('ItemList', 'ItemList'), ('LocalBusiness', 'LocalBusiness')], default='', help_text='Automatski: BlogPosting za blog, WebPage za CMS stranice.', max_length=32, verbose_name='Schema.org tip')),
                ('seo_score', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='SEO ocena')),
                ('readability_score', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Ocena čitljivosti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tip sadržaja')),
            ],
            options={
                'verbose_name': 'SEO metapodaci',
                'verbose_name_plural': 'SEO metapodaci',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='seo_seometa_content_a438cb_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='seo_unique_content_object')],
            },
        ),
    ]
