# Generated by Django 5.2.15 on 2026-06-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0009_robots_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seometadata',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Ručni override. Prazno = automatski sa javne adrese članka (bez UTM i paginacionih parametara).', verbose_name='Kanonski URL'),
        ),
        migrations.AlterField(
            model_name='seometadata',
            name='is_cornerstone',
            field=models.BooleanField(default=False, help_text='Označite glavne tematske članke. Supporting objave treba da linkuju ka njima; sistem prikazuje orphan upozorenja i preporuke klastera.', verbose_name='Cornerstone sadržaj'),
        ),
        migrations.AlterField(
            model_name='seometadata',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Preporučeno: 1200×630 px, JPEG/PNG/WebP, max 8 MB. Prazno = istaknuta slika ili prva slika iz buildera.', storage='blog_images', upload_to='seo/og/%Y/%m/', verbose_name='Open Graph slika'),
        ),
    ]
