# Generated by Django 5.2.15 on 2026-06-07 06:53

import apps.core.storage_aliases
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0010_alter_seometadata_canonical_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seometadata',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Preporučeno: 1200×630 px, JPEG/PNG/WebP, max 8 MB. Prazno = istaknuta slika ili prva slika iz buildera.', storage=apps.core.storage_aliases.blog_images_storage, upload_to='seo/og/%Y/%m/', verbose_name='Open Graph slika'),
        ),
        migrations.AlterField(
            model_name='seometadata',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Preporučeno: 1200×630 px za summary_large_image. Prazno = Open Graph slika ili istaknuta slika.', storage=apps.core.storage_aliases.blog_images_storage, upload_to='seo/twitter/%Y/%m/', verbose_name='Twitter slika'),
        ),
    ]
