# Generated by Django 5.2.15 on 2026-07-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0013_include_in_sitemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text='Putanja bez domena, npr. /blog/stari-naslov/.', max_length=255, unique=True, verbose_name='Stara putanja')),
                ('new_path', models.CharField(blank=True, help_text='Odredište preusmerenja. Prazno za 410 (uklonjena stranica).', max_length=255, verbose_name='Nova putanja')),
                ('redirect_type', models.CharField(choices=[('301', '301 — trajno preusmerenje'), ('302', '302 — privremeno preusmerenje'), ('410', '410 — stranica trajno uklonjena')], default='301', max_length=3, verbose_name='Tip')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivno')),
                ('note', models.CharField(blank=True, help_text='Interna napomena, npr. razlog promene slug-a.', max_length=255, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
            ],
            options={
                'verbose_name': 'Preusmerenje',
                'verbose_name_plural': 'Preusmerenja',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['old_path', 'is_active'], name='seo_redirec_old_pat_fcf221_idx')],
            },
        ),
    ]
