# Generated by Django 5.2.14 on 2026-06-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layout', '0001_squashed_wagtail_removed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('meta_title', models.CharField(blank=True, help_text='Preporučeno: 50–60 karaktera. Prazno = naslov stranice.', max_length=70, verbose_name='Meta naslov')),
                ('meta_description', models.TextField(blank=True, help_text='Preporučeno: 150–160 karaktera.', max_length=320, verbose_name='Meta opis')),
                ('title', models.CharField(max_length=255, verbose_name='Naslov')),
                ('slug', models.SlugField(help_text='Jedinstveni identifikator u URL-u (npr. projekti).', max_length=255, unique=True, verbose_name='Slug')),
                ('page_type', models.CharField(choices=[('standard', 'Standardna stranica'), ('projekti', 'Projekti')], default='standard', max_length=32, verbose_name='Tip stranice')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivna')),
            ],
            options={
                'verbose_name': 'CMS stranica',
                'verbose_name_plural': 'CMS stranice',
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('page_type', 'projekti')), fields=('page_type',), name='layout_cmspage_unique_projekti_type')],
            },
        ),
    ]
