# Generated by Django 5.2.14 on 2026-06-05 19:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('layout', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Redosled')),
                ('block_type', models.CharField(choices=[('heading', 'Naslov'), ('text', 'Tekst'), ('image', 'Slika'), ('button', 'Dugme'), ('video', 'Video'), ('spacer', 'Razmak'), ('divider', 'Linija'), ('gallery', 'Galerija'), ('carousel', 'Karusel')], default='text', max_length=20, verbose_name='Tip bloka')),
                ('heading_text', models.CharField(blank=True, max_length=255, verbose_name='Tekst naslova')),
                ('heading_level', models.CharField(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], default='h2', max_length=2, verbose_name='Nivo naslova')),
                ('heading_align', models.CharField(choices=[('left', 'Levo'), ('center', 'Centar'), ('right', 'Desno')], default='left', max_length=10, verbose_name='Poravnanje naslova')),
                ('text_content', models.TextField(blank=True, verbose_name='Tekst')),
                ('text_align', models.CharField(choices=[('left', 'Levo'), ('center', 'Centar'), ('right', 'Desno')], default='left', max_length=10, verbose_name='Poravnanje teksta')),
                ('image', models.ImageField(blank=True, storage='blog_images', upload_to='builder/images/%Y/%m/', verbose_name='Slika')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Alt tekst slike')),
                ('image_caption', models.CharField(blank=True, max_length=255, verbose_name='Opis slike')),
                ('image_link_url', models.URLField(blank=True, verbose_name='Link slike')),
                ('button_label', models.CharField(blank=True, max_length=120, verbose_name='Tekst dugmeta')),
                ('button_url', models.URLField(blank=True, verbose_name='URL dugmeta')),
                ('button_style', models.CharField(choices=[('primary', 'Primarno'), ('outline', 'Obrub'), ('dark', 'Tamno')], default='primary', max_length=16, verbose_name='Stil dugmeta')),
                ('button_open_new_tab', models.BooleanField(default=False, verbose_name='Otvori u novom tabu')),
                ('video_source', models.CharField(choices=[('embed', 'Embed URL (YouTube/Vimeo)'), ('file', 'Video fajl')], default='embed', max_length=10, verbose_name='Izvor videa')),
                ('video_embed_url', models.URLField(blank=True, help_text='YouTube ili Vimeo embed link.', verbose_name='Embed URL')),
                ('video_file', models.FileField(blank=True, storage='project_videos', upload_to='builder/videos/%Y/%m/', verbose_name='Video fajl')),
                ('video_poster', models.ImageField(blank=True, storage='blog_images', upload_to='builder/posters/%Y/%m/', verbose_name='Poster slike')),
                ('spacer_height', models.PositiveSmallIntegerField(default=32, verbose_name='Visina razmaka (px)')),
                ('spacer_height_mobile', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Visina razmaka na mobilnom (px)')),
                ('divider_style', models.CharField(choices=[('solid', 'Puna'), ('dashed', 'Isprekidana'), ('dotted', 'Tačkasta')], default='solid', max_length=10, verbose_name='Stil linije')),
                ('divider_width', models.CharField(choices=[('full', 'Puna'), ('contained', 'U okviru')], default='contained', max_length=16, verbose_name='Širina linije')),
                ('carousel_autoplay', models.BooleanField(default=True, verbose_name='Automatska reprodukcija')),
                ('carousel_interval', models.PositiveSmallIntegerField(default=5, verbose_name='Interval (sekunde)')),
            ],
            options={
                'verbose_name': 'Blok',
                'verbose_name_plural': 'Blokovi',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Redosled')),
                ('width', models.PositiveSmallIntegerField(default=12, help_text='12 = puna širina, 6 = pola, 4 = trećina.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Širina (1–12)')),
            ],
            options={
                'verbose_name': 'Kolona',
                'verbose_name_plural': 'Kolone',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Redosled')),
                ('gap', models.CharField(choices=[('none', 'Bez'), ('sm', 'Malo'), ('md', 'Srednje'), ('lg', 'Veliko')], default='md', max_length=16, verbose_name='Razmak između kolona')),
                ('vertical_align', models.CharField(choices=[('top', 'Gore'), ('center', 'Centar'), ('bottom', 'Dole')], default='top', max_length=16, verbose_name='Vertikalno poravnanje')),
            ],
            options={
                'verbose_name': 'Red',
                'verbose_name_plural': 'Redovi',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockCarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Redosled')),
                ('image', models.ImageField(storage='blog_images', upload_to='builder/carousel/%Y/%m/', verbose_name='Slika')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt tekst')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Naslov')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Opis')),
                ('link_url', models.URLField(blank=True, verbose_name='Link')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_slides', to='layout.block', verbose_name='Blok')),
            ],
            options={
                'verbose_name': 'Slajd karusela',
                'verbose_name_plural': 'Slajdovi karusela',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Redosled')),
                ('image', models.ImageField(storage='blog_images', upload_to='builder/gallery/%Y/%m/', verbose_name='Slika')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt tekst')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Opis')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='layout.block', verbose_name='Blok')),
            ],
            options={
                'verbose_name': 'Slika galerije',
                'verbose_name_plural': 'Slike galerije',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='block',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='layout.column', verbose_name='Kolona'),
        ),
        migrations.AddField(
            model_name='column',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='layout.row', verbose_name='Red'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Redosled')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='ID sadržaja')),
                ('admin_label', models.CharField(blank=True, help_text='Interni naziv u adminu (nije vidljiv posetiocima).', max_length=120, verbose_name='Admin oznaka')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Vidljivo')),
                ('background_color', models.CharField(blank=True, help_text='Hex (#f5f5f5) ili CSS boja. Prazno = podrazumevano.', max_length=32, verbose_name='Boja pozadine')),
                ('padding_top', models.CharField(choices=[('none', 'Bez'), ('sm', 'Malo'), ('md', 'Srednje'), ('lg', 'Veliko')], default='md', max_length=16, verbose_name='Razmak gore')),
                ('padding_bottom', models.CharField(choices=[('none', 'Bez'), ('sm', 'Malo'), ('md', 'Srednje'), ('lg', 'Veliko')], default='md', max_length=16, verbose_name='Razmak dole')),
                ('container_width', models.CharField(choices=[('contained', 'U okviru kontejnera'), ('full', 'Puna širina')], default='contained', max_length=16, verbose_name='Širina kontejnera')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tip sadržaja')),
            ],
            options={
                'verbose_name': 'Sekcija',
                'verbose_name_plural': 'Sekcije',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='row',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='layout.section', verbose_name='Sekcija'),
        ),
    ]
