# Generated by Django 5.2.14 on 2026-06-05 19:53

import django.db.models.deletion
from django.db import migrations, models


def migrate_carousel_slides(apps, schema_editor):
    Block = apps.get_model("layout", "Block")
    BlockCarouselSlide = apps.get_model("layout", "BlockCarouselSlide")
    Carousel = apps.get_model("layout", "Carousel")
    CarouselItem = apps.get_model("layout", "CarouselItem")

    for block in Block.objects.filter(block_type="carousel"):
        carousel, _ = Carousel.objects.get_or_create(
            block=block,
            defaults={
                "autoplay": getattr(block, "carousel_autoplay", True),
                "show_arrows": True,
                "show_dots": True,
                "speed_ms": 500,
                "interval_seconds": getattr(block, "carousel_interval", 5),
            },
        )
        for slide in BlockCarouselSlide.objects.filter(block=block).order_by("order", "pk"):
            CarouselItem.objects.create(
                carousel=carousel,
                order=slide.order,
                image=slide.image,
                alt_text=slide.alt_text,
                title=slide.title,
                description=slide.caption,
                button_text="",
                button_url=slide.link_url,
                button_open_new_tab=False,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("layout", "0003_block_column_row_blockcarouselslide_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "autoplay",
                    models.BooleanField(
                        default=True, verbose_name="Automatska reprodukcija"
                    ),
                ),
                (
                    "show_arrows",
                    models.BooleanField(
                        default=True, verbose_name="Strelice za navigaciju"
                    ),
                ),
                (
                    "show_dots",
                    models.BooleanField(
                        default=True, verbose_name="Tačkice (paginacija)"
                    ),
                ),
                (
                    "speed_ms",
                    models.PositiveSmallIntegerField(
                        default=500,
                        help_text="Trajanje animacije prelaska između slajdova.",
                        verbose_name="Brzina tranzicije (ms)",
                    ),
                ),
                (
                    "interval_seconds",
                    models.PositiveSmallIntegerField(
                        default=5,
                        verbose_name="Interval automatske reprodukcije (sek)",
                    ),
                ),
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carousel",
                        to="layout.block",
                        verbose_name="Blok",
                    ),
                ),
            ],
            options={
                "verbose_name": "Karusel",
                "verbose_name_plural": "Karuseli",
            },
        ),
        migrations.CreateModel(
            name="CarouselItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Redosled"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage="blog_images",
                        upload_to="builder/carousel/%Y/%m/",
                        verbose_name="Slika",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt tekst"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Naslov"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "button_text",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Tekst dugmeta"
                    ),
                ),
                (
                    "button_url",
                    models.URLField(blank=True, verbose_name="URL dugmeta"),
                ),
                (
                    "button_open_new_tab",
                    models.BooleanField(
                        default=False, verbose_name="Otvori dugme u novom tabu"
                    ),
                ),
                (
                    "carousel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="layout.carousel",
                        verbose_name="Karusel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stavka karusela",
                "verbose_name_plural": "Stavke karusela",
                "ordering": ["order", "pk"],
                "abstract": False,
            },
        ),
        migrations.RunPython(migrate_carousel_slides, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="block",
            name="carousel_autoplay",
        ),
        migrations.RemoveField(
            model_name="block",
            name="carousel_interval",
        ),
        migrations.DeleteModel(
            name="BlockCarouselSlide",
        ),
    ]
