# Generated by Django 5.2.14 on 2026-06-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0004_carousel_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmspage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Ostavite prazno — automatski se generiše sa javne adrese stranice.', verbose_name='Kanonski URL'),
        ),
        migrations.AlterField(
            model_name='cmspage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Neaktivne stranice nisu dostupne posetiocima.', verbose_name='Aktivna'),
        ),
        migrations.AlterField(
            model_name='cmspage',
            name='page_type',
            field=models.CharField(choices=[('standard', 'Standardna stranica'), ('projekti', 'Projekti')], default='standard', help_text='Tip „Projekti” prikazuje stranicu na /projekti/.', max_length=32, verbose_name='Tip stranice'),
        ),
        migrations.AlterField(
            model_name='cmspage',
            name='slug',
            field=models.SlugField(help_text='Za tip „Projekti” koristite slug „projekti”.', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='cmspage',
            name='title',
            field=models.CharField(help_text='Interni i SEO naslov stranice.', max_length=255, verbose_name='Naslov'),
        ),
    ]
