# Generated by Django 5.2.14 on 2026-06-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0005_cmspage_canonical_url_alter_cmspage_is_active_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cmspage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('page_type', 'projekti'), _negated=True), ('slug', 'projekti'), _connector='OR'), name='layout_cmspage_projekti_slug'),
        ),
    ]
