# Generated by Django 5.2.14 on 2026-06-05 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layout", "0006_cmspage_projekti_slug_constraint"),
    ]

    operations = [
        migrations.RenameField(
            model_name="column",
            old_name="width",
            new_name="desktop_width",
        ),
        migrations.AlterField(
            model_name="column",
            name="desktop_width",
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text="Desktop (≥1200px). 12 = puna širina, 6 = pola, 4 = trećina.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Širina na desktopu",
            ),
        ),
        migrations.AddField(
            model_name="column",
            name="tablet_width",
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text="Tablet (768–1199px).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Širina na tabletu",
            ),
        ),
        migrations.AddField(
            model_name="column",
            name="mobile_width",
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text="Mobil (≤767px).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Širina na mobilnom",
            ),
        ),
    ]
