# Generated by Django 5.2.14 on 2026-06-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0007_column_responsive_widths'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON podaci za nove tipove blokova (FAQ, cene, mape…).', verbose_name='Konfiguracija bloka'),
        ),
        migrations.AlterField(
            model_name='cmspage',
            name='page_type',
            field=models.CharField(choices=[('standard', 'Standardna stranica'), ('projekti', 'Projekti')], default='standard', help_text='Standardne stranice: /stranica/<slug>/. Tip „Projekti”: fiksna ruta /projekti/.', max_length=32, verbose_name='Tip stranice'),
        ),
    ]
