# Generated by Django 5.2.14 on 2026-06-05 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0008_block_config_plugin_architecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjektiPage',
            fields=[
            ],
            options={
                'verbose_name': 'Stranica Projekti',
                'verbose_name_plural': 'Stranica Projekti',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('layout.cmspage',),
        ),
    ]
