# Generated by Django 5.2.14 on 2026-06-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0009_projekti_page_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmspage',
            name='page_type',
            field=models.CharField(choices=[('standard', 'Standardna stranica'), ('projekti', 'Projekti')], default='standard', help_text='Javna stranica projekata koristi tip „Projekti” i rutu /projekti/.', max_length=32, verbose_name='Tip stranice'),
        ),
    ]
