# Generated by Django 5.2.15 on 2026-06-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0011_remove_standard_cms_page_type'),
        ('seo', '0002_migrate_legacy_seo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmspage',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='cmspage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='cmspage',
            name='meta_title',
        ),
    ]
