# Generated by Django 5.2.15 on 2026-06-07 06:53

import apps.core.storage_aliases
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0012_remove_legacy_seo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='image',
            field=models.ImageField(blank=True, storage=apps.core.storage_aliases.blog_images_storage, upload_to='builder/images/%Y/%m/', verbose_name='Slika'),
        ),
        migrations.AlterField(
            model_name='block',
            name='video_file',
            field=models.FileField(blank=True, storage=apps.core.storage_aliases.project_videos_storage, upload_to='builder/videos/%Y/%m/', verbose_name='Video fajl'),
        ),
        migrations.AlterField(
            model_name='block',
            name='video_poster',
            field=models.ImageField(blank=True, storage=apps.core.storage_aliases.blog_images_storage, upload_to='builder/posters/%Y/%m/', verbose_name='Poster slike'),
        ),
        migrations.AlterField(
            model_name='blockgalleryimage',
            name='image',
            field=models.ImageField(storage=apps.core.storage_aliases.blog_images_storage, upload_to='builder/gallery/%Y/%m/', verbose_name='Slika'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(storage=apps.core.storage_aliases.blog_images_storage, upload_to='builder/carousel/%Y/%m/', verbose_name='Slika'),
        ),
    ]
