# Generated by Django 5.2.16 on 2026-07-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0016_remove_cmspage_authoring_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmspage',
            name='page_version',
            field=models.PositiveIntegerField(default=0, help_text='Raste monotono pri svakoj promeni page sadržaja (čuvanje, konflikti).', verbose_name='Verzija stranice'),
        ),
    ]
